site_name: My Docs
site_url: https://ekstrom-ibm.github.io/mkdocs-test/
site_author: Jan Ekstr√∏m
site_description: "This is the first MKDocs site"

nav:
  - Home: /
  - Welcome to contribute: index.md
  - Get started: getting_started.md
  - Pre-Requisites: prereqs.md
  - Add content: add_content.md
  - Create new lab: create_new.md
  - Deploy to IBM Cloud: deploy.md
  - About: about.md

theme: readthedocs
markdown_extensions:
  - attr_list
  - admonition

